# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [ ]:
print(np.__version__, np.__config__)

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
# Method 1:
a1 = np.random.rand(2, 3, 5)

# Method 2:
a2 = np.random.random((2, 3, 5))

# Method 3:
a3 = np.random.randn(2, 3, 5)


### 4. Print a.


In [7]:
a1, a2, a3

(array([[[0.42845721, 0.23318462, 0.00518833, 0.47647204, 0.11090869],
         [0.24349679, 0.22961122, 0.06320084, 0.42844096, 0.81634873],
         [0.48603633, 0.03340404, 0.10643201, 0.70721811, 0.27740242]],
 
        [[0.86211391, 0.00412022, 0.76298317, 0.87051945, 0.02470028],
         [0.32859584, 0.26672522, 0.86138667, 0.15447437, 0.69166924],
         [0.51765325, 0.3553373 , 0.64388275, 0.35312064, 0.38478098]]]),
 array([[[0.63629511, 0.29020814, 0.37203816, 0.76535906, 0.0129871 ],
         [0.68492007, 0.47498809, 0.09824865, 0.97633485, 0.85506972],
         [0.92170279, 0.78756084, 0.09185735, 0.77797717, 0.11051886]],
 
        [[0.50860893, 0.13764774, 0.40254126, 0.24041891, 0.06449602],
         [0.0879415 , 0.66870643, 0.22672407, 0.42360929, 0.0172454 ],
         [0.85280732, 0.58854633, 0.3098321 , 0.78464827, 0.04858068]]]),
 array([[[ 0.31194607, -0.67489783,  0.72928605, -2.12265714,
           0.52809344],
         [-0.17277196,  0.44097181,  0.07274452,  

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
a1.size == b.size

True


### 8. Are you able to add a and b? Why or why not?


In [11]:
# You cannot add them directly, since they have different shapes. 
# If you try to add them, it will give you a ValueError:

a1 + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [12]:
c = b.transpose(1, 2, 0)
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [14]:
# It works now because both arrays have the same shape

d = a1 + c
d

array([[[1.42845721, 1.23318462, 1.00518833, 1.47647204, 1.11090869],
        [1.24349679, 1.22961122, 1.06320084, 1.42844096, 1.81634873],
        [1.48603633, 1.03340404, 1.10643201, 1.70721811, 1.27740242]],

       [[1.86211391, 1.00412022, 1.76298317, 1.87051945, 1.02470028],
        [1.32859584, 1.26672522, 1.86138667, 1.15447437, 1.69166924],
        [1.51765325, 1.3553373 , 1.64388275, 1.35312064, 1.38478098]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
a1, d

# The values in d are 1 bigger than the values in a1. This is because d = a1 + c and the values in c are all 1.

(array([[[0.42845721, 0.23318462, 0.00518833, 0.47647204, 0.11090869],
         [0.24349679, 0.22961122, 0.06320084, 0.42844096, 0.81634873],
         [0.48603633, 0.03340404, 0.10643201, 0.70721811, 0.27740242]],
 
        [[0.86211391, 0.00412022, 0.76298317, 0.87051945, 0.02470028],
         [0.32859584, 0.26672522, 0.86138667, 0.15447437, 0.69166924],
         [0.51765325, 0.3553373 , 0.64388275, 0.35312064, 0.38478098]]]),
 array([[[1.42845721, 1.23318462, 1.00518833, 1.47647204, 1.11090869],
         [1.24349679, 1.22961122, 1.06320084, 1.42844096, 1.81634873],
         [1.48603633, 1.03340404, 1.10643201, 1.70721811, 1.27740242]],
 
        [[1.86211391, 1.00412022, 1.76298317, 1.87051945, 1.02470028],
         [1.32859584, 1.26672522, 1.86138667, 1.15447437, 1.69166924],
         [1.51765325, 1.3553373 , 1.64388275, 1.35312064, 1.38478098]]]))


### 12. Multiply a and c. Assign the result to e.


In [19]:
e = a1 * c
e

array([[[0.42845721, 0.23318462, 0.00518833, 0.47647204, 0.11090869],
        [0.24349679, 0.22961122, 0.06320084, 0.42844096, 0.81634873],
        [0.48603633, 0.03340404, 0.10643201, 0.70721811, 0.27740242]],

       [[0.86211391, 0.00412022, 0.76298317, 0.87051945, 0.02470028],
        [0.32859584, 0.26672522, 0.86138667, 0.15447437, 0.69166924],
        [0.51765325, 0.3553373 , 0.64388275, 0.35312064, 0.38478098]]])



### 13. Does e equal to a? Why or why not?


In [20]:
# True, because c = 1.

e == a1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [23]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
d_max, d_min, d_mean

(np.float64(1.8705194463541404),
 np.float64(1.0041202210671571),
 np.float64(1.390928854865696))


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [25]:
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [27]:
f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [33]:
d, f

(array([[[1.42845721, 1.23318462, 1.00518833, 1.47647204, 1.11090869],
         [1.24349679, 1.22961122, 1.06320084, 1.42844096, 1.81634873],
         [1.48603633, 1.03340404, 1.10643201, 1.70721811, 1.27740242]],
 
        [[1.86211391, 1.00412022, 1.76298317, 1.87051945, 1.02470028],
         [1.32859584, 1.26672522, 1.86138667, 1.15447437, 1.69166924],
         [1.51765325, 1.3553373 , 1.64388275, 1.35312064, 1.38478098]]]),
 array([[[ 75.,  25.,  25.,  75.,  25.],
         [ 25.,  25.,  25.,  75.,  75.],
         [ 75.,  25.,  25.,  75.,  25.]],
 
        [[ 75.,   0.,  75., 100.,  25.],
         [ 25.,  25.,  75.,  25.,  75.],
         [ 75.,  25.,  75.,  25.,  25.]]]))

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [34]:
f = f.astype(object)

f[d == d_min] = 'A'
f[(d > d_min) & (d < d_mean)] = 'B'
f[d == d_mean] = 'C'
f[(d > d_mean) & (d < d_max)] = 'D'
f[d == d_max] = 'E'
f

array([[['D', 'B', 'B', 'D', 'B'],
        ['B', 'B', 'B', 'D', 'D'],
        ['D', 'B', 'B', 'D', 'B']],

       [['D', 'A', 'D', 'E', 'B'],
        ['B', 'B', 'D', 'B', 'D'],
        ['D', 'B', 'D', 'B', 'B']]], dtype=object)